# Generated by Django 3.0.5 on 2021-04-11 04:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sunexposure',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 10, 21, 40, 13, 269818)),
        ),
    ]
