# Generated by Django 3.0.5 on 2021-04-11 06:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210410_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sunexposure',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 10, 23, 29, 40, 454859)),
        ),
        migrations.AlterModelTable(
            name='sunexposure',
            table='sunexposures',
        ),
    ]
